<div style="text-align: left; background-color:#FFF6B3; font-family: Trebuchet MS; color:#7C444F; padding: 12px; line-height:1.25;border-radius:1px; margin-bottom: 0em; text-align: center; font-size: 58px;border-style: solid;border-color: dark green;">Billionaires Analysis</div>

<div style="text-align: center;">
    <img src="https://static.vecteezy.com/system/resources/thumbnails/007/945/339/small_2x/millionaire-logo-design-icon-design-template-element-lettet-b-design-vector.jpg" alt="Image" style="width: 300px;">
</div>

   <a id='top'></a>
<div class="list-group" id="list-tab" role="tablist"></div>

## <div style="text-align: left; background-color:#FFF6B3; font-family: Trebuchet MS; color: #7C444F; padding: 15px; line-height:1;border-radius:1px; margin-bottom: 0em; text-align: center; font-size: 25px;border-style: solid;border-color: dark green;">📝 TABLE OF CONTENT📝</div>
    
[I. Dataset Description](#1)
    
[II. Import Libraries](#2)
    
[III. Dataset Exploration](#3)
  * [1. Understand the Dataset](#3.1)
  * [2. Meaning of rows and columns](#3.2)
  * [3. Check and Handle Duplicate Rows](#3.3)
  * [4. Examine Data Types of Columns](#3.4)
    
[IV. 1D Data Analysis and Exploration](#4)
  * [1. Numerical Columns](#4.1)
  * [2. Non-Numerical Columns](#4.2)
  * [3. Handle Missing Values in Columns and Rows](#4.3)
    
[V. 2D Data Analysis and Exploration](#5)
  * [1. Analyze Correlation Between Numerical Columns](#5.1)
  * [2. Analyze Two Numerical Variables Using Scatter Plot](#5.2)
  * [3. Analyze Numerical and Categorical Variables Using Bar Chart](#5.3)
  * [4. Analyze Proportions Between Two Categorical Variables](#5.4)

[VI. 3D Data Analysis and Exploration](#6)

[VII. Detailed Feature Analysis](#7)
  * [1. Feature Name](#7.1)
  * [2. Features SibSp and Parch](#7.2)

[VIII. Questions and Answers](#8)
  * [1. Question 1](#8.1)
  * [2. Question 2](#8.2)

[IX. Conclusion](#9)

<a id="1"></a>
## <div style="text-align: left; background-color:#FFF6B3; font-family: Trebuchet MS; color: #7C444F; padding: 15px; line-height:1;border-radius:1px; margin-bottom: 0em; text-align: center; font-size: 25px;border-style: solid;border-color: dark green;">I. Dataset Description 📌</div>

<div style="border-radius: 10px;
            border: #0A0104 solid;
            padding: 15px;
            background-color: #FEFAE0;
            font-size: 110%;
            text-align: left;
            color: black;">
   <span style="color:'black' ;">

[Billionaires Statistics Dataset (2023)](https://www.kaggle.com/datasets/nelgiriyewithana/billionaires-statistics-dataset/data) provides comprehensive insights into the world's billionaires, covering their wealth, industries, and personal demographics. Key features include `rankings, net worth, industries of operation, and geographical details such as countries and cities of residence`. Additionally, the dataset captures information on self-made versus inherited wealth, age, gender, and organization affiliations, offering a detailed view of global wealth distribution and its demographic context.

Beyond individual attributes, the dataset includes economic indicators such as GDP, CPI, tax rates, and education enrollment rates by country, enabling a broader analysis of how macroeconomic factors correlate with billionaire wealth. Potential use cases range from demographic analysis and wealth distribution studies to geospatial and economic trend analyses, making it a valuable resource for understanding global wealth dynamics and their societal implications.

<a id="2"></a>
## <div style="text-align: left; background-color:#FFF6B3; font-family: Trebuchet MS; color: #7C444F; padding: 15px; line-height:1;border-radius:1px; margin-bottom: 0em; text-align: center; font-size: 25px;border-style: solid;border-color: dark green;">II. Import Libraries 📖</div>

In [11]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

<a id="3"></a>
<div style="text-align: left; background-color:#FFF6B3; font-family: Trebuchet MS; color: #7C444F; padding: 15px; line-height:1; border-radius:1px; margin-bottom: 0em; text-align: center; font-size: 25px; border-style: solid; border-color: dark green;">
    III. Dataset Exploration 🔎
</div>

In [12]:
data = pd.read_csv('./data/Billionaires-Statistics-Dataset.csv')

In [13]:
data

,rank,finalWorth,category,personName,age,country,city,source,industries,countryOfCitizenship,organization,selfMade,status,gender,birthDate,lastName,firstName,title,date,state,residenceStateRegion,birthYear,birthMonth,birthDay,cpi_country,cpi_change_country,gdp_country,gross_tertiary_education_enrollment,gross_primary_education_enrollment_country,life_expectancy_country,tax_revenue_country_country,total_tax_rate_country,population_country,latitude_country,longitude_country
0,1,211000,Fashion & Retail,Bernard Arnault & family,74.0,France,Paris,LVMH,Fashion & Retail,France,LVMH Moët Hennessy Louis Vuitton,False,U,M,3/5/1949 0:00,Arnault,Bernard,Chairman and CEO,4/4/2023 5:01,NaN,NaN,1949.0,3.0,5.0,110.05,1.1,"$2,715,518,274,227",65.6,102.5,82.5,24.2,60.7,6.705989e+07,46.227638,2.213749
1,2,180000,Automotive,Elon Musk,51.0,United States,Austin,"Tesla, SpaceX",Automotive,United States,Tesla,True,D,M,6/28/1971 0:00,Musk,Elon,CEO,4/4/2023 5:01,Texas,South,1971.0,6.0,28.0,117.24,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,3.282395e+08,37.090240,-95.712891
2,3,114000,Technology,Jeff Bezos,59.0,United States,Medina,Amazon,Technology,United States,Amazon,True,D,M,1/12/1964 0:00,Bezos,Jeff,Chairman and Founder,4/4/2023 5:01,Washington,West,1964.0,1.0,12.0,117.24,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,3.282395e+08,37.090240,-95.712891
3,4,107000,Technology,Larry Ellison,78.0,United States,Lanai,Oracle,Technology,United States,Oracle,True,U,M,8/17/1944 0:00,Ellison,Larry,CTO and Founder,4/4/2023 5:01,Hawaii,West,1944.0,8.0,17.0,117.24,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,3.282395e+08,37.090240,-95.712891
4,5,106000,Finance & Investments,Warren Buffett,92.0,United States,Omaha,Berkshire Hathaway,Finance & Investments,United States,Berkshire Hathaway Inc. (Cl A),True,D,M,8/30/1930 0:00,Buffett,Warren,CEO,4/4/2023 5:01,Nebraska,Midwest,1930.0,8.0,30.0,117.24,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,3.282395e+08,37.090240,-95.712891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2635,2540,1000,Healthcare,Yu Rong,51.0,China,Shanghai,Health clinics,Healthcare,China,NaN,True,D,M,12/14/1971 0:00,Yu,Rong,NaN,4/4/2023 5:01,NaN,NaN,1971.0,12.0,14.0,125.08,2.9,"$19,910,000,000,000",50.6,100.2,77.0,9.4,59.2,1.397715e+09,35.861660,104.195397
2636,2540,1000,Food & Beverage,"Richard Yuengling, Jr.",80.0,United States,Pottsville,Beer,Food & Beverage,United States,NaN,False,E,M,3/10/1943 0:00,Yuengling,Richard,NaN,4/4/2023 5:01,Pennsylvania,Northeast,1943.0,3.0,10.0,117.24,7.5,"$21,427,700,000,000",88.2,101.8,78.5,9.6,36.6,3.282395e+08,37.090240,-95.712891
2637,2540,1000,Manufacturing,Zhang Gongyun,60.0,China,Gaomi,Tyre manufacturing machinery,Manufacturing,China,NaN,True,R,M,12/18/1962 0:00,Zhang,Gongyun,NaN,4/4/2023 5:01,NaN,NaN,1962.0,12.0,18.0,125.08,2.9,"$19,910,000,000,000",50.6,100.2,77.0,9.4,59.2,1.397715e+09,35.861660,104.195397
2638,2540,1000,Real Estate,Zhang Guiping & family,71.0,China,Nanjing,Real estate,Real Estate,China,NaN,True,D,M,8/21/1951 0:00,Zhang,Guiping,NaN,4/4/2023 5:01,NaN,NaN,1951.0,8.0,21.0,125.08,2.9,"$19,910,000,000,000",50.6,100.2,77.0,9.4,59.2,1.397715e+09,35.861660,104.195397
2639,2540,1000,Diversified,Inigo Zobel,66.0,Philippines,Makati,Diversified,Diversified,Philippines,NaN,False,R,M,11/1/1956 0:00,Zobel,Inigo,NaN,4/4/2023 5:01,NaN,NaN,1956.0,11.0,1.0,129.61,2.5,"$376,795,508,680",35.5,107.5,71.1,14.0,43.1,1.081166e+08,12.879721,121.774017

<a id="3.1"></a>
### **<span style="font-family: Trebuchet MS; color:#D8A25E;">1. Understand the Dataset</span>**

<h2 style="color:#10375C ; font-family: Trebuchet MS; font-size: 1em "><b> Totals number of rows and columns</b></h2>

In [14]:
n_rows, n_cols = data.shape
print(f'The dataset has {n_rows} rows and {n_cols} columns')

The dataset has 2640 rows and 35 columns

<h2 style="color:#10375C ; font-family: Trebuchet MS; font-size: 1em "><b> Meaning of rows and columns </b></h2>

In [15]:
data.columns

Index(['rank', 'finalWorth', 'category', 'personName', 'age', 'country',
       'city', 'source', 'industries', 'countryOfCitizenship', 'organization',
       'selfMade', 'status', 'gender', 'birthDate', 'lastName', 'firstName',
       'title', 'date', 'state', 'residenceStateRegion', 'birthYear',
       'birthMonth', 'birthDay', 'cpi_country', 'cpi_change_country',
       'gdp_country', 'gross_tertiary_education_enrollment',
       'gross_primary_education_enrollment_country', 'life_expectancy_country',
       'tax_revenue_country_country', 'total_tax_rate_country',
       'population_country', 'latitude_country', 'longitude_country'],
      dtype='object')

<div style="border-radius: 10px;
            border: #0A0104 solid;
            padding: 15px;
            background-color: #FEFAE0;
            font-size: 110%;
            text-align: left;
            color: black;">
   <span style="color:'black' ;">

- **Each row** represents the information of a single billionaire.
- The columns have the following meanings:
   1. `personName`: the full name of the billionaire.
   2. `age`: The age of the billionaire at the time of data collection.
   3. `country`: The nationality of the billionaire.
   4. `source`: The primary source of the billionaire's wealth, such as technology, real estate, r inheritance.
   5. `industries`: The industry or sector in which the billionaire operates or invested.
   6. `worth (USD)`: The billionaire's net worth in US dollars.
   7. `selfMade`: Indicates whether the billionaire's wealth was self-made or inherited.
      - **1**: Self-made
      - **0**: Inherited
   8. `gender`: The gender oof the billionaire.
   9. `status`: Indicates the living status of the billionaire.
      - **Alive** or **Dead**.
   10. `birthDate`: The date of birth of the billionaire.
   11. `citizenship`: The citizenship or passport country of the billionaire.
   12. `organization`: The name of the organization with which the billionaire is most closely associated.
   13. `title`: The role or title of the billionaire in their organization(e.g., CEO, Founder).
   14. `birthCountry`: The country where the billionaire was born.
   15. `birthState`: The sate or province where the billionaire was born (if applicable).
   16. `birthCity`: The city where the billionaire was born.
   17. `education`: The level of education achieved by the billionaire (e.g., Bachelor's, Master's, PhD).
   18. `university`: The name ò the univerdity attended by the billionaire (if applicable).
   19. `maritalStatus`: The mariatl status of the the billionaire (e.g., Maried, Single).
   20. `children`: The number of children the billionaire has.
   21. `political`: Indicates the political affiliation or involvement of the billionaire.
   22. `philanthropic`: Indicates the philanthropic efforts of the billionaire.
   23. `residence`: The city or country where the billionaire currently resides.
   24. `yatchs`: Indicates whether the billionaire owns yatchs.
   25. `jets`: Indicates whether the billionaire owns private jets. 
   26. `art`: Indicates whether the billionaire owns notable art collections. 
   27. `sports`: Indicates whether the billionaire owns or invests in sports teams. 
   28. `realEstate`: Indicates significant investments in real estate by the billionaire. 
   29. `luxuryGoods`: Indicates investments or ownership of luxury goods. 
   30. `luxuryVehicles`: Indicates whether the billionaire owns luxury vehicles. 
   31. `divorced`: Indicates whether the billionaire has been divorced. 
   32. `foundations`: Indicates the presence of charitable foundations started by the billionaire. 
   33. `politicalParty`: The political party the billionaire supports (if known). 
   34. `bio`: A brief biography or additional information about the billionaire. 
   35. `sourceUrl`: The source or URL from where the data was collected.
   </span>
</div>

<h2 style="color:#10375C ; font-family: Trebuchet MS; font-size: 1em "><b> Check and Handle Duplicate Rows </b></h2>

In [16]:
duplicated_rows = data.duplicated().sum()

if duplicated_rows == 0:
    print('There are no duplicate rows, meaning each row in the DataFrame is unique.')
    print('So we do not need to keep processing duplicate lines')
else:
    print(f'There are {duplicated_rows} duplicate rows so we will delete {duplicated_rows} rows')
    data = data.drop_duplicates()
    print(f'After removing duplicate rows, there are {data.shape[0]} rows remaining')

There are no duplicate rows, meaning each row in the DataFrame is unique.
So we do not need to keep processing duplicate lines

<h2 style="color:#10375C ; font-family: Trebuchet MS; font-size: 1em "><b> Examine Data Types of Columns </b></h2>

In [17]:
data.dtypes.to_frame('Data Type')

                                           Data Type
rank                                           int64
finalWorth                                     int64
category                                      object
personName                                    object
age                                          float64
country                                       object
city                                          object
source                                        object
industries                                    object
countryOfCitizenship                          object
organization                                  object
selfMade                                        bool
status                                        object
gender                                        object
birthDate                                     object
lastName                                      object
firstName                                     object
title                                         object
date                                          object
state                                         object
residenceStateRegion                          object
birthYear                                    float64
birthMonth                                   float64
birthDay                                     float64
cpi_country                                  float64
cpi_change_country                           float64
gdp_country                                   object
gross_tertiary_education_enrollment          float64
gross_primary_education_enrollment_country   float64
life_expectancy_country                      float64
tax_revenue_country_country                  float64
total_tax_rate_country                       float64
population_country                           float64
latitude_country                             float64
longitude_country                            float64

<div style="border-radius: 10px;
            border: #0A0104 solid;
            padding: 15px;
            background-color: #FEFAE0;
            font-size: 110%;
            text-align: left;
            color: black;">
   <span style="color:'black' ;">

   The `age`, `birthDay`, `birthMonth`, and `birthYear` columns in the dataset currently have incorrect data types, being stored as **float64** instead of the intended **int64**. Similarly, the `birthDate` and `date` columns are stored as **object**, whereas they should be of type **datetime64**. The next step involves converting these columns to their appropriate data types to ensure consistency and accuracy in the dataset.

   </span>
</div>

In [18]:
cols_to_convert = ['age', 'birthDay', 'birthMonth', 'birthYear']
data[cols_to_convert] = data[cols_to_convert].fillna(0).astype('Int64')

date_cols = ['birthDate', 'date']
data[date_cols] = data[date_cols].apply(pd.to_datetime, errors='coerce')

data.dtypes.to_frame('Data Type')

                                                 Data Type
rank                                                 int64
finalWorth                                           int64
category                                            object
personName                                          object
age                                                  Int64
country                                             object
city                                                object
source                                              object
industries                                          object
countryOfCitizenship                                object
organization                                        object
selfMade                                              bool
status                                              object
gender                                              object
birthDate                                   datetime64[ns]
lastName                                            object
firstName                                           object
title                                               object
date                                        datetime64[ns]
state                                               object
residenceStateRegion                                object
birthYear                                            Int64
birthMonth                                           Int64
birthDay                                             Int64
cpi_country                                        float64
cpi_change_country                                 float64
gdp_country                                         object
gross_tertiary_education_enrollment                float64
gross_primary_education_enrollment_country         float64
life_expectancy_country                            float64
tax_revenue_country_country                        float64
total_tax_rate_country                             float64
population_country                                 float64
latitude_country                                   float64
longitude_country                                  float64

<a id="3"></a>
<div style="text-align: left; background-color:#FFF6B3; font-family: Trebuchet MS; color: #7C444F; padding: 15px; line-height:1; border-radius:1px; margin-bottom: 0em; text-align: center; font-size: 25px; border-style: solid; border-color: dark green;">
    IV. 1D Data Analysis and Exploration 📶
</div>

<div style="border-radius: 10px;
            border: #0A0104 solid;
            padding: 15px;
            background-color: #FEFAE0;
            font-size: 110%;
            text-align: left;
            color: black;">
   <span style="color:'black' ;">

   To explore the distribution of columns, we will follow these steps:

- Numeric columns:
   - Calculate and interpret **summary statistics** of the columns
   - Draw **histograms** to better understand the distribution of columns

- Non-numeric columns:
   - Calculate the number of **unique values** in each column
   - Draw **histograms** to better understand the distribution of columns

- Missing values ​​and handling:
   - Calculate the number of missing values ​​in each column, each row and handle them

   </span>
</div>

<a id="3.1"></a>
### **<span style="font-family: Trebuchet MS; color:#D8A25E;">1. Numerical Columns</span>**

<h2 style="color:#10375C ; font-family: Trebuchet MS; font-size: 1em "><b> Statistic Summary </b></h2>

<div style="border-radius: 10px;
            border: #0A0104 solid;
            padding: 15px;
            background-color: #FEFAE0;
            font-size: 110%;
            text-align: left;
            color: black;">
   <span style="color:'black' ;">

   For numeric columns, we will calculate:

- Percentage (0 to 100) of missing values

- Minimum
- Lower quartile
- Median
- Upper quartile
- Maximum

We will save the result to DataFrame `num_col_dist_df`, where:
- Column names are the names of numeric columns in `data`
- Row names: `missing_ratio`, `min`, `low_quartile`, `median`, `upper_quartile`, `max`

   </span>
</div>

In [19]:
pd.set_option('display.max_columns', None)
numeric_cols = data.select_dtypes(exclude=['object']).columns
num_col_dist_df = data[numeric_cols].copy()
missing_percentage = num_col_dist_df.isna().mean() * 100

num_col_dist_df = num_col_dist_df.describe(percentiles=[.25, .5, .75]).round(2)
num_col_dist_df.loc['missing ratios'] = missing_percentage

num_col_dist_df

,rank,finalWorth,age,birthDate,date,birthYear,birthMonth,birthDay,cpi_country,cpi_change_country,gross_tertiary_education_enrollment,gross_primary_education_enrollment_country,life_expectancy_country,tax_revenue_country_country,total_tax_rate_country,population_country,latitude_country,longitude_country
count,2640.00,2640.00,2640.0,2564,2640,2640.0,2640.0,2640.0,2456.000000,2456.000000,2458.000000,2459.000000,2458.000000,2457.000000,2458.000000,2.476000e+03,2476.000000,2476.000000
mean,1289.16,4623.79,63.54,1957-08-10 08:18:54.477379072,2023-04-04 05:01:10.909091072,1900.84,5.58,11.75,127.760000,4.360000,67.230000,102.860000,78.120000,12.550000,43.960000,5.102053e+08,34.900000,12.580000
min,1.00,1000.00,0.0,1921-09-11 00:00:00,2023-04-04 05:01:00,0.0,0.0,0.0,99.550000,-1.900000,4.000000,84.700000,54.300000,0.100000,9.900000,3.801900e+04,-40.900000,-106.350000
25%,659.00,1500.00,55.0,1948-02-04 18:00:00,2023-04-04 05:01:00,1947.0,2.0,1.0,117.240000,1.700000,50.600000,100.200000,77.000000,9.600000,36.600000,6.683440e+07,35.860000,-95.710000
50%,1312.00,2300.00,65.0,1957-07-15 12:00:00,2023-04-04 05:01:00,1957.0,5.0,10.0,117.240000,2.900000,65.600000,101.800000,78.500000,9.600000,41.200000,3.282395e+08,37.090000,10.450000
75%,1905.00,4200.00,74.0,1966-09-23 12:00:00,2023-04-04 05:01:00,1966.0,9.0,20.0,125.080000,7.500000,88.200000,102.600000,80.900000,12.800000,59.100000,1.366418e+09,40.460000,104.200000
max,2540.00,211000.00,101.0,2004-05-06 00:00:00,2023-04-04 09:01:00,2004.0,12.0,31.0,288.570000,53.500000,136.600000,142.100000,84.200000,37.200000,106.300000,1.397715e+09,61.920000,174.890000
std,739.69,9834.24,16.53,NaN,NaN,327.58,3.78,9.98,26.450000,3.620000,21.340000,4.710000,3.730000,5.370000,12.150000,5.542447e+08,17.000000,86.760000
missing ratios,0.00,0.00,0.0,2.878788,0.0,0.0,0.0,0.0,6.969697,6.969697,6.893939,6.856061,6.893939,6.931818,6.893939,6.212121e+00,6.212121,6.212121

<h2 style="color:#034914 ;font-size: 1em "><b> ⭐ Comments </b></h2>

<div style="border-radius: 10px;
            border: #0A0104 solid;
            padding: 15px;
            background-color: #FEFAE0;
            font-size: 110%;
            text-align: left;
            color: black;">
   <span style="color:'black' ;">

   

   </span>
</div>

In [23]:
col = data.select_dtypes(exclude=['object']).columns
color = ['#009392', '#72aaa1', '#b1c7b3', '#f1eac8', '#e5b9ad', '#d98994', '#d0bbff']

# num_cols = len(col)
# ncols = 6
# nrows = (num_cols + ncols - 1) // ncols

# fig, ax = plt.subplots(nrows=nrows, ncols=ncols, figsize=(20, 5 * nrows))
# ax = ax.flatten()  # Flatten to make indexing easier

# for i, column in enumerate(col):
#     p = sns.histplot(data=data[column], ax=ax[i], color=color[i % len(color)])
#     p.axes.set_title(f"Distribution of {column}", fontsize=14, color='k', weight='bold')
#     p.axes.set_xlabel(column, fontsize=11, weight='bold')
#     p.axes.set_ylabel('Count', fontsize=10, weight='bold')
#     p.grid(color='#95a5a6', linestyle='--', linewidth=1, axis='y', alpha=0.4)

# for i in range(len(col), len(ax)):
#     fig.delaxes(ax[i])

# sns.despine(left=True, bottom=True)
# plt.tight_layout()
# plt.show()

# plt.figure(figsize=(20, 5))
# p = sns.histplot(data=data['Fare'], color=color[-1], kde=True)
# p.set_title('Distribution of Fare', fontsize=14, color='k', weight='bold')
# p.set_xlabel('Fare', fontsize=11, weight='bold')
# p.set_ylabel('Count', fontsize=10, weight='bold')
# p.grid(color='#95a5a6', linestyle='--', linewidth=1, axis='y', alpha=0.4)

# sns.despine(left=True, bottom=True)
# plt.show()